---

- hosts: [frontend]
  remote_user: '{{ remote_user }}'

  tasks:
    - name: Install nodejs and npm
      apt:
        name: ['npm', 'nodejs']

    - name: Checkout latest master from git
      git:
        repo: '{{ app_repo }}'
        dest: '{{ app_dir }}'
        force: true
        version: master
      become: yes
      become_user: '{{ app_user }}'

    - name: Install packages based on package.json
      npm:
        path: '{{ app_frontend_dir }}'
        state: latest
      become: yes
      become_user: '{{ app_user }}'

    - name: Build latest master for production
      shell: 'cd {{ app_frontend_dir }}/ && npm run build'
      args:
        executable: /bin/bash
      become: yes
      become_user: '{{ app_user }}'

    - name: Restart service enrique, in all cases
      service:
        name: enrique
        state: restarted
